apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
  namespace: dev

spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
      - name: api
        image: contacts-api:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__ServiceBusConnection
          valueFrom:
            secretKeyRef:
              name: servicebus-secret
              key: ServiceBusConnection
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: DB_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: registration-service-config
              key: DB_CONNECTION_STRING
        - name: SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: registration-service-config
              key: SERVICE_PORT
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  namespace: dev
  labels:
    app: consumer-service
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - name: consumer-service
        image: contacts-consumer:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ConnectionStrings__ServiceBusConnection
          valueFrom:
            secretKeyRef:
              name: servicebus-secret
              key: ServiceBusConnection
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: DB_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: registration-service-config
              key: DB_CONNECTION_STRING
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      imagePullSecrets:
      - name: regcred