apiVersion: v1
kind: Service
metadata:
  name: registration-service
  labels:
    app: registration-service

spec:
  selector:
    app: registration-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
