apiVersion: v1
kind: ConfigMap
metadata:
  name: registration-service-config
  namespace: default
  labels:
    app: registration-service
    environment: development

data:
  DB_CONNECTION_STRING: "Server=tcp:contacts-database.database.windows.net,1433;Initial Catalog=contacts;Persist Security Info=False;User ID=alexandre;Password=@2789Hl1987;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  SERVICE_PORT: "8080"
