apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service
  labels:
    app: registration-service
    environment: development

spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
      - name: registration-service-container
        image: contacts-registry-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: registration-service-config
              key: DB_CONNECTION_STRING
        - name: SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: registration-service-config
              key: SERVICE_PORT
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      imagePullSecrets:
        - name: regcred
