name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'  

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar
        run: dotnet build --configuration Release --no-restore

      # Experimente uma das duas abordagens abaixo:

      # Opção 1: Sem a flag --no-build
      - name: Executar testes (sem --no-build)
        run: dotnet test --verbosity normal

      # Opção 2: Especificando o arquivo de solução
      #- name: Executar testes (com solução)
      #  run: dotnet test ContactsRegistrationService.sln --no-build --verbosity normal
